### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by jnbohrer**
Edited the **meetings** _page_:
    \* edit button can't be pressed if there are no meetings 
    \* done button switches back to edit after deletion of only meeting

### CODE REVIEW

**Comment by ChosunOne** [comment]
Tested on Android 6.0.1

**Comment by MuyangAmigo** [comment]
Tested on iOS 9.3.1

**Comment by MuyangAmigo** [comment]
Tested on iOS 9.3.1, everything works.

**Comment by jnbohrer** [comment]
notSoSmallFixes (The branch _formerly_ known as **smallFixes**)

**Comment by ChosunOne** [comment]
Tested on Android 6.0.1 and code reviewed and approved.

**Pull request merged**
