### PR TITLE
Confirm Delete

### PR DESCRIPTION
**Pull request by jnbohrer**
Added alert to confirm whether the user wants to delete a meeting

### CODE REVIEW

**Comment by benmel** [comment]
Works on iOS

**Comment by benmel** [comment]
Code looks good

**Comment by MuyangAmigo** [comment]
One more test on iOS simulator (4s). Everything works.

**Comment by Grygoree** [comment]
Tested android simulator.  Everything except request meeting works (which is ok since it's a fault of my android OS version).

**Pull request merged**
